export const caseData = [
  {
    caseNumber: "1234-A988",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "New",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "Escalated",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
  {
    caseNumber: "1234-A987",
    plaintiff: "John Doe",
    dateOfClaim: "4/30/22",
    claimStatus: "In progress",
    actionRequired: "Intake Process",
    targetCompletion: "7/30/22",
  },
];
